### ISSUE TITLE
bug- player field in config.json comes out empty if user does not choose a player

### ISSUE THREAD

**Issue by qascade** [qascade/yast#36]
**Description**: 
If you run `./yast setup` and do not choose a player. The config.json gets created with empty string. This is not a desired behaviour intended for the aforementioned command. 

**How to fix this bug**
- Option 1: Throw an error if user does not choose a player. 
Removing Option 2: We should let the user quit as per his/her discretion and the config file should not be created, if the setup model was quit before chosing a player. The reason is very simple, we can't force the user to setup yast, its his/her choice. 
- ~~Option2: We can refresh the model to ask the user to choose a player until he finally chooses.~~

Also, please make sure that config.json is not created or deleted if created, if user does not choose a player while running `yast setup` for the first time. 

Please note `yast setup` and `yast config --reset` are aliases of each other. So, if you could find a way to remove duplicacy of code anywhere, it is highly appreciated.

**Comment by murugesanp** [comment]
I would to like to take this bug. Could you assign it to me?

**Comment by murugesanp** [comment]
This bug seems to be already fixed. Never be able to de-select player, so the state player not be chosen never possible.

**Comment by qascade** [comment]
Thanks for the PR. I have seen the code. Will test it locally and then merge the PR.
