### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by naman-ng** [qascade/yast#43]
Since this project is a part of hactoberfest and in general a CODE_OF_CONDUCT.md should be there and rename contributions.md to CONTRIBUTING.md as a general convention

**Comment by naman-ng** [comment]
Hello, please assign this issue to me.
I'll do the needful. 
Thank you :)

**Comment by qascade** [comment]
I will add the code of conduct

**Comment by qascade** [comment]
Please look at other issues.

**Comment by qascade** [comment]
Sure, thanks for pointing that out. Assigning this to you.

**Comment by qascade** [comment]
Also while you are at it, update `WebTorrent API` to `WebTorrent CLI` at the start of the project description in the readme.

**Comment by naman-ng** [comment]
Sure will do that!
Is it okay if I make the pull request on 1st Oct, for the hactoberfest? :)

**Comment by qascade** [comment]
I don't think this issue is gonna get accepted by hacktoberfest as writing CODE_OF_CONDUCT is the responsibility of the maintainer. So, even if you raise this PR. It will become invalid, governance wise speaking. So, I'd reccomend you look at other issues.

**Comment by qascade** [comment]
So, if you want to contribute you can add this [link](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md) to CODE_OF_CONDUCT but I will not add `hacktoberfest` tag to this. So, you can raise the PR right now.

**Comment by qascade** [comment]
On second thoughts, I will add the CODE_OF_CONDUCT myself. Thanks for pointing out.
