### ISSUE TITLE
Make the repo Community Standard Compliant

### ISSUE THREAD

**Issue by notafk-rajat** [qascade/yast#47]
The doc named contribution.md should be changed to contributing.md according to community standards.

Refer to this link - https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

The issue can be noticed when one goes to - Insights->Community Standards.

It Looks like this right now 

<img width="683" alt="community standards" src="https://user-images.githubusercontent.com/84857474/193452426-e100c62a-33c5-447f-aaed-6ab684b2c50f.png">

Our goal should be to get green ticks on all the standards eventually. This issue is only of contribution standard.

**Comment by qascade** [comment]
@notafk-rajat Thanks for pointing this out. Assigning this issue to you.

**Comment by qascade** [comment]
I will request the modifications if needed in PR review.

**Comment by notafk-rajat** [comment]
Thanks for assigning the issue. I'll try to fix it now.

**Comment by notafk-rajat** [comment]
I have made a push request but I'm not sure if I did it right or not. Please check.

**Comment by qascade** [comment]
@notafk-rajat Can you please raise a PR from your repo.
