### ISSUE TITLE
testing linux support for yast

### ISSUE THREAD

**Issue by qascade** [qascade/yast#52]
## Description
We believe that `yast` supports linux environments because the same FileSystem API works on both Linux and MacOS. `yast` has been tested and vetted for properly working on macOS. But we need to test the same for Linux OSes such as Ubuntu, Fedora, Debian based distros. 
If in some environment, it does not work? Is there a way to fix it? Do we need to make some changes to the code or provide additional documentation instructions/installation instructions for different environments? 

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest 2022. This is a beginner issue, should only require small code changes and some documentation changes.

**Comment by moazfarrukh** [comment]
can i take up this issue?

**Comment by moazfarrukh** [comment]
i currently have ubuntu installed on my system

**Comment by qascade** [comment]
Sure, you need to install and check whether you are able to stream using yast. If no, report any blockers here, so that we can fix that accordingly in this PR. If yes, then you have to update the docs accordingly. Add extra steps that are required to install on Ubuntu. Thanks.

**Comment by moazfarrukh** [comment]
@qascade i did a test of yast on my system. and i faced two problems. first the npm install command requires sudo rights. else running it as it gives access denied error. 
![image](https://user-images.githubusercontent.com/21291203/194717156-9d11202f-4835-4e2b-a4c1-f9c48ec2dc18.png)

**Comment by moazfarrukh** [comment]
second is that after running the go build command it does not make a yast binary hence ./yast command does not run.
the go run main.go command works tho
![image](https://user-images.githubusercontent.com/21291203/194717242-9da01edd-399e-4d8c-95b9-1736d3c89a87.png)
 
![image](https://user-images.githubusercontent.com/21291203/194717295-6665410b-7530-4103-8f10-95d7dc82fff8.png)

**Comment by moazfarrukh** [comment]
for reference:
my golang version is 1.18.1
while ubuntu version is Ubuntu 22.04.1

**Comment by qascade** [comment]
You can do `go build` instead of `fo run main.go` to build `yast` binary. Then `./yast -- help` will work.

**Comment by moazfarrukh** [comment]
> You can do `go build` instead of `go run main.go` to build `yast` binary. Then `./yast --help` will work.

oh i just tried that that actually works.
the problem was with go build ./ ...
which is written in the documentation

**Comment by moazfarrukh** [comment]
@qascade i tried retrying the install process  the ./ ... after go build seems to be the culprit
![image](https://user-images.githubusercontent.com/21291203/194717710-ff763f2d-98bb-4376-b313-1fb8f6f44f98.png)

**Comment by qascade** [comment]
So, `go build` works but `go build ./...` doesn't.

**Comment by qascade** [comment]
Use a VPN and search for a movie and see if a stream starts.

**Comment by moazfarrukh** [comment]
> Use a VPN and search for a movie and see if a stream starts.
@qascade yep it seems to be working. but it doesn't take the word after blank space for search for some reason
![image](https://user-images.githubusercontent.com/21291203/194718094-e83ac5dc-3f53-466a-872c-7c693c53cfc0.png)

**Comment by qascade** [comment]
`./yast "free guy"` put multiple words separated with spaces in inverted commas.

**Comment by qascade** [comment]
Thanks for testing this. Please udate the docs. Add Note below every point where modification is needed. Put something like `Note - Use sudo in ubuntu` or use `go build` instead. Also add the point for space separated case as well.

**Comment by qascade** [comment]
Also can you share the screenshot of results list. Just for my reference.

**Comment by moazfarrukh** [comment]
> Thanks for testing this. Please update the docs. Add Note below every point where modification is needed. Put something like `Note - Use sudo in ubuntu` or use `go build` instead. Also add the point for space separated case as well.

ok sure

**Comment by moazfarrukh** [comment]
> Also can you share the screenshot of results list. Just for my reference.
here are the search results
![image](https://user-images.githubusercontent.com/21291203/194718915-0ec06ba3-f23f-47cb-bf7e-ec8b6403faf0.png)

**Comment by moazfarrukh** [comment]
@qascade i have made the pull request. kindly review
