### ISSUE TITLE
Add Windows support to yast

### ISSUE THREAD

**Issue by qascade** [qascade/yast#53]
## Description
As the config utilities were developed keeping Unix FileSystem in mind. We need to add support for creating config files of `yast` in the Windows File System. This issue was brought to the notice by @notafk-rajat in #28.

> Hey @qascade , So I was going through readme.md to setup yast on my local environment. I got stuck at step 6 for a while so I had to do `go run main.go` to run the program. So we might need to check into that too.
> 
> But still I'm not able to anything after that. `.yast/setup` is not working
> 
> <img alt="Screenshot 2022-10-04 233759" width="827" src="https://user-images.githubusercontent.com/84857474/193893628-3d68e64a-1aaa-429d-a18e-19eed2ae3995.png">
> 
> Also webtorrent-cli is not installing correctly
> 
> <img alt="image" width="814" src="https://user-images.githubusercontent.com/84857474/193894332-05f3799a-30b3-45b5-901e-7846531a4ff6.png">

## How are you planning to resolve on this issue?
First I would check which operating system, I am currently running yast on. Then accordingly I will choose a path for `YAST_WORKDIR` defined in `utils/constants.go`. Then, make changes to config functions.

## Acceptance Criteria
1. No behavioral changes should be observed while running `yast` on environments other than windows. 
2. `yast` should show the same behavior as other environments on windows. 
3. `TUI` should behave almost identically to its behavior in Unix environments, If this is not possible, we have to find alternatives or fallback accordingly. 

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest 2022. This is a issue for experienced developer. You need experience of working with different environments. Have understanding of how all modules of `yast` work internally and have knowledge of both Unix and 
Windows File System APIs and how to work with both of them in Go.

**Comment by notafk-rajat** [comment]
When you say Unix based, do you mean MacOS? Did you create yast on MacOS?

**Comment by qascade** [comment]
Yes, I developed yast on macOS.

**Comment by notafk-rajat** [comment]
1. Have to use `go build rather than `go build ./...`.
2.  Cannot use cmd for `yast` as it throws an error on running any yast command like `./yast --help` throws `'.' is not recognized as an internal or external command, operable program, or batch file.`
3. Use PowerShell instead.

Also, there is not output showing here as well. I have selected VLC as my default player. Maybe it's a problem on my end,, I'll look into it soon.

**Comment by qascade** [comment]
I dont think it's gonna work in windows as we have not configured yast config file creation as per windows file system. I have described the issue in detail above.

**Comment by qascade** [comment]
As mentioned in #51 , we were not able to successfully setup `yast` in wsl. So, for windows, we will provide a docker support. This will solve support problems in other platforms as well.

**Comment by qascade** [comment]
@notafk-rajat Can you add a `support.md` in `docs` directory and document all our discussions in there. I will be closing this issue after updating the support.md and will create a separate issue for docker support.

**Comment by qascade** [comment]
Will track docker image creation in #58.
