### ISSUE TITLE
Build a website to store the documentation.

### ISSUE THREAD

**Issue by bayaosborn** [qascade/yast#56]
Will build a website to store the documentation(For the moment, suggestions are open). It will be easy for users to access how they can install yast at the moment. Preferred languages are simply HTML and CSS. It will be an easy UI. Will store it on Netlify and can be changed to your account if set up. I'm used to Netlify hosting.

**Comment by qascade** [comment]
Thanks for your suggestion. But the yast project's documentation is not that big that we need separate hosting for documentation. We will need a separate hosting for `go-webtorrent` but that is still under design phase.

**Comment by bayaosborn** [comment]
Ok. Great.
