### ISSUE TITLE
Update Github actions node version to 16

### ISSUE THREAD

**Issue by sudhinm** [qascade/yast#66]
## Description
Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases). Github actions have started using node 16 and the usage of old version in the workflow config is leading to the following warning:
To see the warnings
1. Go to Actions tab in Github
2. Select any succeeded workflow run
3. You will see warnings below the workflow run details.

## Screenshots
<img width="1326" alt="Screenshot 2022-10-26 at 7 16 26 PM" src="https://user-images.githubusercontent.com/34642968/198049085-f3d9d80e-3fd3-49b0-97b4-e96d121ee10e.png">

## Do you want to work on this issue?
No

## How are you planning to resolve on this issue?
We need to upgrade the node version to 16 for the actions that shows warning. Follow this page for [reference](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

## Are you raising this issue under hacktoberfest? (Remove this section if you are not a hacktoberfest participant)
Yes, I'm raising this issue under hacktoberfest.

**Comment by qascade** [comment]
@sudhinm Thanks for making me aware of this.
